/* Generated By:JavaCC: Do not edit this line. AlgoritmaTokenManager.java */
package AlgoritmaYorumlayici;
import java.io.*;
import java.util.*;

/** Token Manager. */
public class AlgoritmaTokenManager implements AlgoritmaConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 37:
         return jjStopAtPos(0, 23);
      case 39:
         return jjStartNfaWithStates_0(0, 26, 118);
      case 40:
         return jjStopAtPos(0, 14);
      case 41:
         return jjStopAtPos(0, 15);
      case 42:
         return jjStopAtPos(0, 21);
      case 43:
         return jjStopAtPos(0, 19);
      case 45:
         return jjStopAtPos(0, 20);
      case 47:
         return jjStartNfaWithStates_0(0, 22, 3);
      case 58:
         return jjStopAtPos(0, 27);
      case 61:
         return jjStartNfaWithStates_0(0, 24, 26);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x0L, 0x1040008010400080L
};
static final long[] jjbitVec2 = {
   0x30000c0000000L, 0xc0000000L, 0x0L, 0x0L
};
static final long[] jjbitVec3 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec5 = {
   0x80000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec6 = {
   0x40000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec7 = {
   0x1000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec8 = {
   0x0L, 0x80000000L, 0x0L, 0x0L
};
static final long[] jjbitVec9 = {
   0x0L, 0x40000000L, 0x0L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 118;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 118:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  else if (curChar == 39)
                  {
                     if (kind > 18)
                        kind = 18;
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 3)
                        kind = 3;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 25)
                        kind = 25;
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if (curChar == 61)
                     jjCheckNAdd(26);
                  else if (curChar == 39)
                     jjCheckNAddTwoStates(23, 24);
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if (curChar == 60)
                     jjCheckNAddTwoStates(26, 30);
                  else if (curChar == 62)
                     jjCheckNAdd(26);
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 10 && kind > 1)
                     kind = 1;
                  break;
               case 2:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(4, 6);
                  break;
               case 4:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(4, 6);
                  break;
               case 5:
                  if (curChar == 47 && kind > 4)
                     kind = 4;
                  break;
               case 6:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjAddStates(3, 4);
                  break;
               case 22:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 23:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 24:
                  if (curChar == 39 && kind > 18)
                     kind = 18;
                  break;
               case 25:
                  if ((0x5000000000000000L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 26:
                  if (curChar == 61 && kind > 25)
                     kind = 25;
                  break;
               case 27:
                  if (curChar == 62)
                     jjCheckNAdd(26);
                  break;
               case 28:
                  if (curChar == 61)
                     jjCheckNAdd(26);
                  break;
               case 29:
                  if (curChar == 60)
                     jjCheckNAddTwoStates(26, 30);
                  break;
               case 30:
                  if (curChar == 62 && kind > 25)
                     kind = 25;
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(0, 2);
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(85, 86);
                  break;
               case 86:
                  if (curChar == 46 && kind > 2)
                     kind = 2;
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAdd(87);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 118:
               case 23:
                  jjCheckNAddTwoStates(23, 24);
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddTwoStates(19, 21);
                  }
                  if (curChar == 71)
                     jjAddStates(5, 11);
                  else if (curChar == 103)
                     jjAddStates(12, 14);
                  else if (curChar == 89)
                     jjAddStates(15, 16);
                  else if (curChar == 98)
                     jjAddStates(17, 18);
                  else if (curChar == 66)
                     jjAddStates(19, 22);
                  else if (curChar == 68)
                     jjAddStates(23, 24);
                  else if (curChar == 73)
                     jjAddStates(25, 26);
                  else if (curChar == 69)
                     jjAddStates(27, 30);
                  else if (curChar == 101)
                     jjAddStates(31, 32);
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 4:
                  jjAddStates(33, 34);
                  break;
               case 8:
                  if (curChar == 122 && kind > 7)
                     kind = 7;
                  break;
               case 9:
               case 83:
                  if (curChar == 97)
                     jjCheckNAdd(8);
                  break;
               case 10:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 114 && kind > 10)
                     kind = 10;
                  break;
               case 12:
               case 55:
                  if (curChar == 117)
                     jjCheckNAdd(11);
                  break;
               case 13:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 101 && kind > 11)
                     kind = 11;
                  break;
               case 15:
               case 50:
               case 52:
                  if (curChar == 115)
                     jjCheckNAdd(14);
                  break;
               case 16:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAddTwoStates(19, 21);
                  break;
               case 20:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(20);
                  break;
               case 21:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAddStates(35, 37);
                  break;
               case 31:
                  if (curChar == 101)
                     jjAddStates(31, 32);
                  break;
               case 32:
                  if (curChar == 114 && kind > 12)
                     kind = 12;
                  break;
               case 33:
               case 35:
               case 41:
               case 45:
                  if (curChar == 101)
                     jjCheckNAdd(32);
                  break;
               case 34:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 37:
                  if (curChar == 69)
                     jjAddStates(27, 30);
                  break;
               case 38:
                  if (curChar == 82 && kind > 12)
                     kind = 12;
                  break;
               case 39:
               case 43:
                  if (curChar == 69)
                     jjCheckNAdd(38);
                  break;
               case 40:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 42:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 47:
                  if (curChar == 73)
                     jjAddStates(25, 26);
                  break;
               case 48:
                  if (curChar == 69 && kind > 11)
                     kind = 11;
                  break;
               case 49:
               case 53:
                  if (curChar == 83)
                     jjCheckNAdd(48);
                  break;
               case 54:
                  if (curChar == 68)
                     jjAddStates(23, 24);
                  break;
               case 56:
                  if (curChar == 82 && kind > 10)
                     kind = 10;
                  break;
               case 57:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 66)
                     jjAddStates(19, 22);
                  break;
               case 59:
                  if (curChar == 97 && kind > 9)
                     kind = 9;
                  break;
               case 60:
               case 67:
               case 74:
               case 77:
                  if (curChar == 108)
                     jjCheckNAdd(59);
                  break;
               case 61:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if (curChar == 65 && kind > 9)
                     kind = 9;
                  break;
               case 64:
               case 70:
                  if (curChar == 76)
                     jjCheckNAdd(63);
                  break;
               case 65:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 69:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 72:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 98)
                     jjAddStates(17, 18);
                  break;
               case 75:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 79:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 89)
                     jjAddStates(15, 16);
                  break;
               case 81:
                  if (curChar == 90 && kind > 7)
                     kind = 7;
                  break;
               case 82:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 88:
                  if (curChar == 103)
                     jjAddStates(12, 14);
                  break;
               case 89:
                  if (curChar == 116 && kind > 8)
                     kind = 8;
                  break;
               case 90:
               case 100:
                  if (curChar == 105)
                     jjCheckNAdd(89);
                  break;
               case 91:
                  if (curChar == 115 && kind > 13)
                     kind = 13;
                  break;
               case 92:
               case 108:
                  if (curChar == 105)
                     jjCheckNAdd(91);
                  break;
               case 93:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 96:
               case 115:
                  if (curChar == 105)
                     jjCheckNAdd(95);
                  break;
               case 97:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 71)
                     jjAddStates(5, 11);
                  break;
               case 101:
                  if (curChar == 84 && kind > 8)
                     kind = 8;
                  break;
               case 102:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 104:
                  if (curChar == 83 && kind > 13)
                     kind = 13;
                  break;
               case 105:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 109:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 113:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 116:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 118:
               case 23:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 0:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 16)
                        kind = 16;
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddTwoStates(19, 21);
                  }
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjAddStates(38, 39);
                  break;
               case 4:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(33, 34);
                  break;
               case 17:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2) && kind > 16)
                     kind = 16;
                  break;
               case 18:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAddTwoStates(19, 21);
                  break;
               case 20:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(20);
                  break;
               case 21:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAddStates(35, 37);
                  break;
               case 36:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 44:
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 46:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 51:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjAddStates(38, 39);
                  break;
               case 68:
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 71:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 78:
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 95:
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2) && kind > 13)
                     kind = 13;
                  break;
               case 103:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 111:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2) && kind > 13)
                     kind = 13;
                  break;
               case 112:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 114:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 118 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   85, 86, 87, 19, 20, 100, 102, 103, 107, 110, 114, 117, 90, 94, 98, 82, 
   83, 76, 79, 62, 66, 69, 72, 55, 57, 49, 50, 40, 42, 44, 46, 34, 
   36, 4, 6, 19, 20, 21, 52, 53, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec1[i2] & l2) != 0L);
      case 1:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         if ((jjbitVec3[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_3(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 1:
         return ((jjbitVec5[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_4(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 1:
         return ((jjbitVec6[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_5(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 1:
         return ((jjbitVec7[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_6(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 1:
         return ((jjbitVec8[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_7(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 1:
         return ((jjbitVec9[i2] & l2) != 0L);
      default :
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\50", "\51", null, null, null, "\53", "\55", "\52", "\57", "\45", "\75", null, 
"\47", "\72", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffff9fL, 
};
static final long[] jjtoSkip = {
   0x60L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[118];
private final int[] jjstateSet = new int[236];
protected char curChar;
/** Constructor. */
public AlgoritmaTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public AlgoritmaTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 118; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
