/* Generated By:JavaCC: Do not edit this line. AlgoritmaConstants.java */
package AlgoritmaYorumlayici;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AlgoritmaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int SATIRNO = 2;
  /** RegularExpression Id. */
  int SAYI = 3;
  /** RegularExpression Id. */
  int YORUM = 4;
  /** RegularExpression Id. */
  int YAZ = 7;
  /** RegularExpression Id. */
  int GIT = 8;
  /** RegularExpression Id. */
  int BASLA = 9;
  /** RegularExpression Id. */
  int DUR = 10;
  /** RegularExpression Id. */
  int ISE = 11;
  /** RegularExpression Id. */
  int EGER = 12;
  /** RegularExpression Id. */
  int GIRIS = 13;
  /** RegularExpression Id. */
  int PARAC = 14;
  /** RegularExpression Id. */
  int PARKAPA = 15;
  /** RegularExpression Id. */
  int TURKCEKARAKTER = 16;
  /** RegularExpression Id. */
  int DEGISKEN = 17;
  /** RegularExpression Id. */
  int METIN = 18;
  /** RegularExpression Id. */
  int TOPLA = 19;
  /** RegularExpression Id. */
  int CIKAR = 20;
  /** RegularExpression Id. */
  int CARP = 21;
  /** RegularExpression Id. */
  int BOL = 22;
  /** RegularExpression Id. */
  int MOD = 23;
  /** RegularExpression Id. */
  int ESIT = 24;
  /** RegularExpression Id. */
  int KARSILASTIR = 25;
  /** RegularExpression Id. */
  int TIRNAK = 26;
  /** RegularExpression Id. */
  int IKINOKTA = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<SATIRNO>",
    "<SAYI>",
    "<YORUM>",
    "\" \"",
    "\"\\t\"",
    "<YAZ>",
    "<GIT>",
    "<BASLA>",
    "<DUR>",
    "<ISE>",
    "<EGER>",
    "<GIRIS>",
    "\"(\"",
    "\")\"",
    "<TURKCEKARAKTER>",
    "<DEGISKEN>",
    "<METIN>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "<KARSILASTIR>",
    "\"\\\'\"",
    "\":\"",
  };

}
